### ISSUE TITLE
Add ability to add prefix and postfix

### ISSUE THREAD

**Issue by djkz** [sgruhier/foundation_rails_helper#103]
Foundation gives you a number of options to add prefix and postfix to your form inputs with a `<span>`

It would be nice if that functionality transferred over to the form helper through an option.

**Comment by dsandstrom** [comment]
Good idea, however, I feel it might be a mess to have to deal with column classes.

One of their examples:
```html
<div class="row collapse">
  <div class="small-3 large-2 columns">
    <span class="prefix">http://</span>
  </div>
  <div class="small-9 large-10 columns">
    <input type="text" placeholder="Enter your URL...">
  </div>
</div>
```
The erb might be:
```erb
<%= f.text_field :url, label: "URL", placeholder: "Enter your URL...", prefix: "http://", prefix_column_class: "small-3 large-2", input_column_class: "small-9 large-10" %>
```

**Comment by dsandstrom** [comment]
Or maybe
```erb
<%= f.text_field :url, label: "URL", placeholder: "Enter your URL...", prefix: "http://", prefix_small_columns: 3, prefix_large_columns: 10 %>
```
Then, subtract 12 from each to get the input's columns classes.

**Comment by dsandstrom** [comment]
Actually, it would be better to keep the prefix settings separate:
```erb
<%= f.text_field :url, label: "URL", placeholder: "Enter your URL...", prefix: { value: "http://", small: 3, large: 10 } %>
```

@djkz, If you want to work on a pull request, we can merge it.

**Comment by djkz** [comment]
It gets a bit complicated if you want to support buttons and mixed prefixes and postfixes. I wonder if using flex would be a cleaner solution? http://philipwalton.github.io/solved-by-flexbox/demos/input-add-ons/

**Comment by dsandstrom** [comment]
That looks nice.  However, does foundation have any flexbox built into their styles?  I don't think we should add css to this gem.

**Comment by djkz** [comment]
Looks like not yet, it's planned for the next version: http://zurb.com/article/1333/foundation-a-new-grid

Wrapping everything into a row and calculating main element's size from the 12 - prefix - postfix is the way to go for now, not sure if it's possible to also support buttons and other elements that they showed in their example. Maybe by passing the content_tag for the element directly into the prefix: property but that can get pretty complicated really fast.

**Comment by dsandstrom** [comment]
As you say, anything more complicated than a span is probably a bad idea.  The user can always fallback to making the row/columns themselves.  And if they only need to [support IE 10+](http://caniuse.com/#feat=flexbox), they can use flexbox.

**Comment by dsandstrom** [comment]
Fix merged.
