### ISSUE TITLE
Radio Button Helper Renders Value in Label

### ISSUE THREAD

**Issue by sshaw** [sgruhier/foundation_rails_helper#106]
```
<%= f.radio_button :import_method, 0 %>
```

Renders:

```
<input type="radio" value="0" checked="checked" name="shop[import_method]" id="shop_import_method_0">
<label class="" for="shop_import_method_0">0</label>
```

**Comment by dsandstrom** [comment]
Thanks.  Can you add "Expected" html?

**Comment by sshaw** [comment]
Okay, looking at this with a clear head I see that this is correct. 

Unlike Rails' default `radio_button` method the helper adds the `label` and need something to display, and the label can be overridden by the `:label` options.
