### ISSUE TITLE
Needs a version bump. 

### ISSUE THREAD

**Issue by JoeWoodward** [sgruhier/foundation_rails_helper#108]
I've just been scratching my head as to why prefix/postfix wasn't working even though it is documented.

It seems that you haven't done a version bump for a while now. master is no longer the same as version 1.0.0

There should be a version bump for each PR introduced.

For any one else trying to get prefix/postfix working, for now you can use the master branch
```
gem 'foundation_rails_helper', git: 'https://github.com/sgruhier/foundation_rails_helper.git', branch: 'master'
```

**Comment by JoeWoodward** [comment]
Also on a side note, I've noticed that you have a typo in the README. 

``` ruby
f.text_field :name, prefix { value: 'foo' small: 2, large: 3 }
```

should be
``` ruby
f.text_field :name, prefix: { value: 'foo' small: 2, large: 3 }
```

**Comment by dgmstuart** [comment]
@JoeWoodward thanks for the nudge - we should indeed release a new version. I'll work out what should go in the changelog and see if I can cut a new gem (though it looks like there might be issues with Travis at the moment?)

I'm not sure where the idea of a version bump for each PR has come from - of course that would be nice, but it's not a practice I've ever come across - probably partly because it's a bit of an ask when we're talking about projects managed by people in their spare time ;)

**Comment by dgmstuart** [comment]
Would you mind raising a PR for the documentation fix while I do that?

**Comment by dgmstuart** [comment]
Oh, you already did - thanks :)

**Comment by dgmstuart** [comment]
@dsandstrom any reason not to release master as 1.1.0?

**Comment by JoeWoodward** [comment]
@dgmstuart you're right, not every repo does bump for each PR. I think it would be a good practice but that's in an ideal world. I'm not sure if you use vim but there's an amazing plugin by tpope called git-bump that makes it super easy to bump the versions. 

Ideally versions should follow the semantic versioning definition (http://semver.org/), hence why I suggested each PR. Or each time a group of PRs are merged. because a PR is going to be either a bug fix or a feature

Obviously this isn't the easiest thing to keep on top off but it looks like you have quite a few people using the gem (114 stars and 74 forks :smile:) so probably a good idea. The issue with not bumping versions is that any new code introduced after the latest version tag will not be included for gems installed via bundler, unless a branch is specified and not the version.

i.e. anyone using bundler and specifying 

`gem 'foundation_rails_helper', '~> 1.0'`

Would not get the newly merged code. Unless they changed it to

`gem 'foundation_rails_helper', github: 'sgruhier/foundation_rails_helper', branch: 'master'`

Using the later syntax would mean that bundler loses version control. This can cause problems if foundation_rails_helper is installed in your codebase (via bundler) a while ago and then a new developer joins a team and runs bundle install. The new team member will have the newest code from the branch which may not match the other developers machines. Whereas if you are always using version numbers all devs will have the same source

**Comment by dgmstuart** [comment]
@JoeWoodward Yup - I'm aware of how Bundler handles pointing at github branches ;) 

As far as I'm aware, semver doesn't say anything about how much (or little) should go into each version bump.

Like I say, we're all just trying to squeeze things in around our actual jobs and lives. Telling open source maintainers how they "should" be doing things might be taken the wrong way.

Hopefully once this Travis issue is sorted out we'll be able to release a new version.

**Comment by JoeWoodward** [comment]
@dgmstuart didn't mean to offend, I appreciate your work. I'm pretty tired so that was probably worded very poorly. If there's anything I can do to help let me know.

**Comment by dgmstuart** [comment]
@JoeWoodward no worries :) We're all good

**Comment by dsandstrom** [comment]
@dgmstuart I see no problems with this (after the PRs are merged of course).

**Comment by dgmstuart** [comment]
@dsandstrom This is now building. FYI: I'll release it now and we can release another version with @JoeWoodward's PRs later when they're merged.

**Comment by dgmstuart** [comment]
1.1.0 is released: https://rubygems.org/gems/foundation_rails_helper

**Comment by dgmstuart** [comment]
@dsandstrom would you like me to add you to the owners on rubygems.org, so that you could push new versions?

http://guides.rubygems.org/command-reference/#owner

**Comment by dsandstrom** [comment]
Yes, that would make things easier.  I sent you an email.
