### ISSUE TITLE
Migrate TravisCI to container-based infrastructure

### ISSUE THREAD

**Issue by dsandstrom** [sgruhier/foundation_rails_helper#110]
https://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

**Comment by dgmstuart** [comment]
This works (i.e. we get the `This job is running on container-based infrastructure` message in https://travis-ci.org/sgruhier/foundation_rails_helper/jobs/93270316), but doesn't address the issue in #111 :(
