### ISSUE TITLE
Support for Foundation 6

### ISSUE THREAD

**Issue by dsandstrom** [sgruhier/foundation_rails_helper#121]
http://foundation.zurb.com/apps/docs/#!/

This will need to be verified since I have not tried it yet.

**Comment by CiTroNaK** [comment]
:+1: 

For example Alert is now Callout.

**Comment by dsandstrom** [comment]
I started a `foundation-6` branch for foundation 6 users.
```
gem 'foundation_rails_helper', github: 'sgruhier/foundation_rails_helper',
                               branch: 'foundation-6'
```

**Comment by iamlenox** [comment]
Is compability with Foundation 6 still pending on this?

**Comment by dsandstrom** [comment]
It works, just have to use branch for now.
