### ISSUE TITLE
Failing spec with Rails 5

### ISSUE THREAD

**Issue by dgmstuart** [sgruhier/foundation_rails_helper#136]
After installing Rails 5 and freshly installing this gem, the following spec fails:

```  
1) FoundationRailsHelper::FormHelper input generators should generate datetime_field input
     Failure/Error: expect(node).to have_css('input[type="datetime"][name="author[forty_two]"]')
       expected #has_css?("input[type=\"datetime\"][name=\"author[forty_two]\"]") to return true, got false
```

It's failing because the `type` is now `datetime-local` (see below). [This has been introduced in Rails 5](http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-datetime_field)
([Old behaviour was to set type as `datetime`](http://api.rubyonrails.org/v4.2.0/classes/ActionView/Helpers/FormHelper.html#method-i-datetime_field))

Here's what the capybara node looks like: 
```
?> a = node.find('input')
=> <Capybara::Node::Simple tag="input" path="/html/body/input">

?> a.native
=> #(Element:0x3ff2ad56bf14 {
  name = "input",
  attributes = [
    #(Attr:0x3ff2ad7d94b8 { name = "value", value = "2011-06-18T20:30:00" }),
    #(Attr:0x3ff2ad7d94a4 { name = "type", value = "datetime-local" }),
    #(Attr:0x3ff2ad7d9490 { name = "name", value = "author[forty_two]" }),
    #(Attr:0x3ff2ad7d947c { name = "id", value = "author_forty_two" })]
  })
```

**Comment by dgmstuart** [comment]
@dsandstrom I guess we can treat this one of two ways: 
1. Treat it as a breaking change and decide that we need a separate branch for Rails 5
2. Decide it doesn't matter much and do a fuzzy match:
```ruby
expect(node).to have_css('input[type^="datetime"]')
```
_(matches inputs with types beginning with "datetime")_

I'll submit a PR for the latter

**Comment by dsandstrom** [comment]
I went with option 1 for the foundation-6 branch.  I never commited the same fix to master, thinking we would stop development on master and focus on foundation-6 only.  Using the fuzzy search is probably better anyhow.

**Comment by dgmstuart** [comment]
Cool - if you think it's OK, would you mind merging?
