### ISSUE TITLE
Release a new gem version for Rails 5 support

### ISSUE THREAD

**Issue by dgmstuart** [sgruhier/foundation_rails_helper#144]
Once #131 is fixed (by merging #142), I think that's the last issue preventing us officially supporting Rails 5, so we should release a new gem version (1.3.0?) at that point.

**Comment by dsandstrom** [comment]
This can be closed, right?

**Comment by dgmstuart** [comment]
heh - we said before that we were supporting rails 5, so I guess it was fine for it to have been a patch release (1.2.2) rather than a feature.
