### ISSUE TITLE
Foundation 6 - Change default button class

### ISSUE THREAD

**Issue by dsandstrom** [sgruhier/foundation_rails_helper#146]
The "radius" class isn't supported anymore.  I suggest we change the default class to `"success button"`

http://foundation.zurb.com/sites/docs/button.html

**Comment by dgmstuart** [comment]
Oh foundation. How you love to mess with your own fundamental design elements 😜

**Comment by dgmstuart** [comment]
Why

**Comment by dsandstrom** [comment]
You can still add a radius to all buttons using `$global-radius`.  This is probably a better approach because it keeps them looking consistent.  In addition, the `'hollow'` class was added, which seems cool.
