### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by dsandstrom** [sgruhier/foundation_rails_helper#155]
TODO:
- [x] Merge #162
- [x] Update readme with new API
- [x] Update changelog

**Comment by dsandstrom** [comment]
Sorry, readme is incorrect.  Use github version until 3.0.0 is released:
```
gem 'foundation_rails_helper',
    git: 'https://github.com/sgruhier/foundation_rails_helper.git'
```

**Comment by josepjaume** [comment]
Hi! Is there any progress on this? We're shipping a gem that needs the latest changes on `foundation_rails_helper` and it's kind of awkward to ask the developer to include GitHub's version.

Anything we can help you with?

Thanks for such a nice work!

**Comment by josepjaume** [comment]
Ping :). What are your goals for 3.0.0? Can I help you? It'd be so useful to get a stable release!

**Comment by dsandstrom** [comment]
See todos

**Comment by dsandstrom** [comment]
A beta is now available:
```
gem 'foundation_rails_helper', '>= 3.0.0.beta3', '< 4.0'
```

**Comment by dsandstrom** [comment]
A release candidate is now available:
```
gem 'foundation_rails_helper', '>= 3.0.0.rc', '< 4.0'
```

**Comment by josepjaume** [comment]
Thanks! Already using it 👍
