### ISSUE TITLE
Make error_for method in form_builder public

### ISSUE THREAD

**Issue by jeffse** [sgruhier/foundation_rails_helper#157]
Is there a compelling reason to keep the `errors_for` method in `FormBuilder` private? I can see a use for this in my own code, where I want to be able to display the error on a property that isn't directly on my form. It's already coded here with the styling appropriate for Foundation, so I'd hate to have to duplicate the code in my own project just to use it.

Way back when, Rails v2 had a method named [error_messages_for](http://apidock.com/rails/ActionView/Helpers/ActiveRecordHelper/error_messages_for) that would display these errors, but it was removed because it [hardcoded certain html and styling](https://news.ycombinator.com/item?id=1263775). That shoudn't be a problem here, because we _want_ to hardcode the Foundation styling.

**Comment by dsandstrom** [comment]
I don't see any reason why it has to stay private.
