### ISSUE TITLE
Exception when a "value" option is set on a Rails label helper.

### ISSUE THREAD

**Issue by paulwittmann** [sgruhier/foundation_rails_helper#53]
Using my fork https://github.com/paulwittmann/foundation_rails_helper (which only updated the tzinfo gem) and Rails 4.1.rc1, I get the following error:

    NoMethodError - undefined method `html_safe' for {:value=>false}:Hash:
     () Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bundler/gems/foundation_rails_helper-03f1be5eb06c/lib/foundation_rails_helper/form_builder.rb:19:in `label'

Everything works fine withe the lastest release from Ruby gems (0.4).

My view code:

    = form_for @order do |f|
      %fieldset
        = f.label :custom_box_design, value: false do
          = f.radio_button :custom_box_design, false, checked: !@order.custom_box_design

Full stack trace:

    Started GET "/orders/3/edit" for 127.0.0.1 at 2014-03-27 23:31:56 +0100
    Processing by OrdersController#edit as HTML
      Parameters: {"id"=>"3"}
      Order Load (0.4ms)  SELECT  "orders".* FROM "orders"  WHERE "orders"."id" = $1 LIMIT 1  [["id", 3]]
      Rendered orders/edit.html.haml within layouts/application (6.5ms)
    Completed 500 Internal Server Error in 12ms

    NoMethodError - undefined method `html_safe' for {:value=>false}:Hash:
       () Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bundler/gems/foundation_rails_helper-03f1be5eb06c/lib/foundation_rails_helper/form_builder.rb:19:in `label'
      app/views/orders/edit.html.haml:4:in `block in _app_views_orders_edit_html_haml__3037086238800668844_70246830429400'
      haml (4.0.5) lib/haml/helpers/action_view_mods.rb:137:in `block (2 levels) in form_for_with_haml'
      haml (4.0.5) lib/haml/helpers.rb:278:in `with_tabs'
      haml (4.0.5) lib/haml/helpers/action_view_mods.rb:137:in `block in form_for_with_haml'
      actionview (4.1.0.rc1) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
      actionview (4.1.0.rc1) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
      haml (4.0.5) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
      actionview (4.1.0.rc1) lib/action_view/helpers/capture_helper.rb:38:in `capture'
      haml (4.0.5) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
      actionview (4.1.0.rc1) lib/action_view/helpers/form_helper.rb:434:in `form_for'
       () Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bundler/gems/foundation_rails_helper-03f1be5eb06c/lib/foundation_rails_helper/action_view_extension.rb:9:in `form_for_with_foundation'
      haml (4.0.5) lib/haml/helpers/action_view_mods.rb:139:in `form_for_with_haml'
      haml (4.0.5) lib/haml/helpers/action_view_xss_mods.rb:28:in `form_for_with_haml_xss'
      app/views/orders/edit.html.haml:1:in `_app_views_orders_edit_html_haml__3037086238800668844_70246830429400'
      actionview (4.1.0.rc1) lib/action_view/template.rb:144:in `block in render'
      activesupport (4.1.0.rc1) lib/active_support/notifications.rb:159:in `block in instrument'
      activesupport (4.1.0.rc1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      activesupport (4.1.0.rc1) lib/active_support/notifications.rb:159:in `instrument'
      actionview (4.1.0.rc1) lib/action_view/template.rb:338:in `instrument'
      actionview (4.1.0.rc1) lib/action_view/template.rb:142:in `render'
      actionview (4.1.0.rc1) lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
      actionview (4.1.0.rc1) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
      activesupport (4.1.0.rc1) lib/active_support/notifications.rb:159:in `block in instrument'
      activesupport (4.1.0.rc1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      activesupport (4.1.0.rc1) lib/active_support/notifications.rb:159:in `instrument'
      actionview (4.1.0.rc1) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
      actionview (4.1.0.rc1) lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'
      actionview (4.1.0.rc1) lib/action_view/renderer/template_renderer.rb:62:in `render_with_layout'
      actionview (4.1.0.rc1) lib/action_view/renderer/template_renderer.rb:53:in `render_template'
      actionview (4.1.0.rc1) lib/action_view/renderer/template_renderer.rb:17:in `render'
      actionview (4.1.0.rc1) lib/action_view/renderer/renderer.rb:42:in `render_template'
      actionview (4.1.0.rc1) lib/action_view/renderer/renderer.rb:23:in `render'
      actionview (4.1.0.rc1) lib/action_view/rendering.rb:99:in `_render_template'
      actionpack (4.1.0.rc1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
      actionview (4.1.0.rc1) lib/action_view/rendering.rb:82:in `render_to_body'
      actionpack (4.1.0.rc1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
      actionpack (4.1.0.rc1) lib/action_controller/metal/renderers.rb:32:in `render_to_body'
      actionpack (4.1.0.rc1) lib/abstract_controller/rendering.rb:25:in `render'
      actionpack (4.1.0.rc1) lib/action_controller/metal/rendering.rb:16:in `render'
      actionpack (4.1.0.rc1) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
      activesupport (4.1.0.rc1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
      /Users/paul/.rbenv/versions/2.1.1/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
      activesupport (4.1.0.rc1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
      actionpack (4.1.0.rc1) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
      actionpack (4.1.0.rc1) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
      activerecord (4.1.0.rc1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
      actionpack (4.1.0.rc1) lib/action_controller/metal/instrumentation.rb:40:in `render'
      actionpack (4.1.0.rc1) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
      actionpack (4.1.0.rc1) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
      actionpack (4.1.0.rc1) lib/abstract_controller/base.rb:189:in `process_action'
      actionpack (4.1.0.rc1) lib/action_controller/metal/rendering.rb:10:in `process_action'
      actionpack (4.1.0.rc1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
      activesupport (4.1.0.rc1) lib/active_support/callbacks.rb:113:in `call'
      activesupport (4.1.0.rc1) lib/active_support/callbacks.rb:166:in `block in halting'
      activesupport (4.1.0.rc1) lib/active_support/callbacks.rb:229:in `block in halting'
      activesupport (4.1.0.rc1) lib/active_support/callbacks.rb:229:in `block in halting'
      activesupport (4.1.0.rc1) lib/active_support/callbacks.rb:166:in `block in halting'
      activesupport (4.1.0.rc1) lib/active_support/callbacks.rb:86:in `run_callbacks'
      actionpack (4.1.0.rc1) lib/abstract_controller/callbacks.rb:19:in `process_action'
      actionpack (4.1.0.rc1) lib/action_controller/metal/rescue.rb:29:in `process_action'
      actionpack (4.1.0.rc1) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
      activesupport (4.1.0.rc1) lib/active_support/notifications.rb:159:in `block in instrument'
      activesupport (4.1.0.rc1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      activesupport (4.1.0.rc1) lib/active_support/notifications.rb:159:in `instrument'
      actionpack (4.1.0.rc1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
      actionpack (4.1.0.rc1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
      activerecord (4.1.0.rc1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
      actionpack (4.1.0.rc1) lib/abstract_controller/base.rb:136:in `process'
      actionview (4.1.0.rc1) lib/action_view/rendering.rb:30:in `process'
      actionpack (4.1.0.rc1) lib/action_controller/metal.rb:195:in `dispatch'
      actionpack (4.1.0.rc1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
      actionpack (4.1.0.rc1) lib/action_controller/metal.rb:231:in `block in action'
      actionpack (4.1.0.rc1) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
      actionpack (4.1.0.rc1) lib/action_dispatch/routing/route_set.rb:48:in `call'
      actionpack (4.1.0.rc1) lib/action_dispatch/journey/router.rb:71:in `block in call'
      actionpack (4.1.0.rc1) lib/action_dispatch/journey/router.rb:59:in `call'
      actionpack (4.1.0.rc1) lib/action_dispatch/routing/route_set.rb:676:in `call'
      dragonfly (1.0.3) lib/dragonfly/middleware.rb:14:in `call'
      bullet (4.8.0) lib/bullet/rack.rb:12:in `call'
      newrelic_rpm (3.7.3.204) lib/new_relic/rack/error_collector.rb:55:in `call'
      newrelic_rpm (3.7.3.204) lib/new_relic/rack/agent_hooks.rb:32:in `call'
      newrelic_rpm (3.7.3.204) lib/new_relic/rack/browser_monitoring.rb:27:in `call'
      newrelic_rpm (3.7.3.204) lib/new_relic/rack/developer_mode.rb:45:in `call'
      rack (1.5.2) lib/rack/etag.rb:23:in `call'
      rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
      rack (1.5.2) lib/rack/head.rb:11:in `call'
      actionpack (4.1.0.rc1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
      actionpack (4.1.0.rc1) lib/action_dispatch/middleware/flash.rb:254:in `call'
      rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
      rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
      actionpack (4.1.0.rc1) lib/action_dispatch/middleware/cookies.rb:551:in `call'
      activerecord (4.1.0.rc1) lib/active_record/query_cache.rb:36:in `call'
      activerecord (4.1.0.rc1) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
      activerecord (4.1.0.rc1) lib/active_record/migration.rb:380:in `call'
      actionpack (4.1.0.rc1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
      activesupport (4.1.0.rc1) lib/active_support/callbacks.rb:82:in `run_callbacks'
      actionpack (4.1.0.rc1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
      actionpack (4.1.0.rc1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
      actionpack (4.1.0.rc1) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
      airbrake (3.1.16) lib/airbrake/rails/middleware.rb:13:in `call'
      better_errors (1.1.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
      better_errors (1.1.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
      better_errors (1.1.0) lib/better_errors/middleware.rb:56:in `call'
      actionpack (4.1.0.rc1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
      actionpack (4.1.0.rc1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
      railties (4.1.0.rc1) lib/rails/rack/logger.rb:38:in `call_app'
      railties (4.1.0.rc1) lib/rails/rack/logger.rb:20:in `block in call'
      activesupport (4.1.0.rc1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
      activesupport (4.1.0.rc1) lib/active_support/tagged_logging.rb:26:in `tagged'
      activesupport (4.1.0.rc1) lib/active_support/tagged_logging.rb:68:in `tagged'
      railties (4.1.0.rc1) lib/rails/rack/logger.rb:20:in `call'
      quiet_assets (1.0.2) lib/quiet_assets.rb:18:in `call_with_quiet_assets'
      actionpack (4.1.0.rc1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
      rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
      rack (1.5.2) lib/rack/runtime.rb:17:in `call'
      activesupport (4.1.0.rc1) lib/active_support/cache/strategy/local_cache.rb:87:in `call'
      rack (1.5.2) lib/rack/lock.rb:17:in `call'
      dragonfly (1.0.3) lib/dragonfly/cookie_monster.rb:9:in `call'
      actionpack (4.1.0.rc1) lib/action_dispatch/middleware/static.rb:64:in `call'
      rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
      airbrake (3.1.16) lib/airbrake/user_informer.rb:16:in `_call'
      airbrake (3.1.16) lib/airbrake/user_informer.rb:12:in `call'
      railties (4.1.0.rc1) lib/rails/engine.rb:515:in `call'
      railties (4.1.0.rc1) lib/rails/application.rb:142:in `call'
      rack (1.5.2) lib/rack/lock.rb:17:in `call'
      rack (1.5.2) lib/rack/content_length.rb:14:in `call'
      rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
      /Users/paul/.rbenv/versions/2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
      /Users/paul/.rbenv/versions/2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
      /Users/paul/.rbenv/versions/2.1.1/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

**Comment by dsandstrom** [comment]
@paulwittmann You have probably moved on, but I see the problem.  You are missing the label text as shown in [api dock](http://apidock.com/rails/ActionView/Helpers/FormHelper/label).

You have:
```haml
= f.label :custom_box_design, value: false
```
When it should be:
```haml
= f.label :custom_box_design, 'Your label', value: false
```
or if you want the default label:
```haml
= f.label :custom_box_design, nil, value: false
```

**Comment by dsandstrom** [comment]
The label helper accepts a block, but you would have to manually add a label string, like so:
```haml
= f.label :custom_box_design, nil, value: false do
  = f.radio_button :custom_box_design, false, checked: !@order.custom_box_design, label: false
  No custom box design
```

**Comment by dsandstrom** [comment]
Feel free to reopen if there is still a problem.
