### ISSUE TITLE
Add new Readme images

### ISSUE THREAD

**Issue by dsandstrom** [sgruhier/foundation_rails_helper#77]
![form-preview](https://cloud.githubusercontent.com/assets/1400414/5790954/54756008-9e67-11e4-9993-f53f336f1fcd.png)
![form-preview-errors](https://cloud.githubusercontent.com/assets/1400414/5790955/56665138-9e67-11e4-92c8-ecad7fb8061f.png)

**Comment by dsandstrom** [comment]
![form-preview](https://cloud.githubusercontent.com/assets/1400414/5790959/8630f9c2-9e67-11e4-807b-f21a4c8faa8a.png)

**Comment by dsandstrom** [comment]
![form-preview](https://cloud.githubusercontent.com/assets/1400414/5791055/f10d45ca-9e6c-11e4-9513-a52e7a56feb9.png)
![form-preview-errors](https://cloud.githubusercontent.com/assets/1400414/5791057/f3455bb6-9e6c-11e4-882d-bbdc76bc9825.png)

**Comment by dsandstrom** [comment]
![flash-preview](https://cloud.githubusercontent.com/assets/1400414/5791070/a13ecedc-9e6d-11e4-83cd-588fa296ef67.png)

**Comment by dgmstuart** [comment]
@dsandstrom Great that you're sorting this out, but what's up with the fonts? Wouldn't it be better to just show the forms just using the default Foundation styles - including the "Helvetica Neue" fount-family?

**Comment by dsandstrom** [comment]
I don't have Helvetica Neue installed on my system (Linux).  So I went with Raleway.  Please add images here if you would like.

**Comment by dsandstrom** [comment]
I have an example app here: https://github.com/dsandstrom/foundation_helper_example that you can use.

**Comment by dgmstuart** [comment]
Here you go @dsandstrom:

Sorry to not have them tidier, but I suck at image handling :( do you mind sorting them out?

![screen shot 2015-01-21 at 21 07 58](https://cloud.githubusercontent.com/assets/393167/5845236/563bf6ec-a1b2-11e4-8f92-afe8e1fda00d.png)
![screen shot 2015-01-21 at 21 08 28](https://cloud.githubusercontent.com/assets/393167/5845237/563c9714-a1b2-11e4-9149-4b671c1f7a6d.png)
![screen shot 2015-01-21 at 21 11 46](https://cloud.githubusercontent.com/assets/393167/5845238/563dc094-a1b2-11e4-8548-2dd2950a60be.png)

**Comment by dgmstuart** [comment]
Oops! Just noticed the little autofill icons. Here are the forms without them:

![screen shot 2015-01-21 at 21 16 21](https://cloud.githubusercontent.com/assets/393167/5845302/d81cfabc-a1b2-11e4-959b-cc3d4601f50f.png)
![screen shot 2015-01-21 at 21 16 36](https://cloud.githubusercontent.com/assets/393167/5845303/d8206378-a1b2-11e4-91eb-4f852b21a4de.png)

**Comment by dsandstrom** [comment]
Trimmed borders.

![foundation-rails-form](https://cloud.githubusercontent.com/assets/1400414/5994195/d9b467ce-aa1e-11e4-914c-f696724b53ed.png)
![foundation-rails-form-error](https://cloud.githubusercontent.com/assets/1400414/5994196/dbf4bc0a-aa1e-11e4-8c18-b7d3b1b370dc.png)

**Comment by dsandstrom** [comment]
Foundation 6 screens
![foundation_rails_helper-before](https://cloud.githubusercontent.com/assets/1400414/18522106/8b981524-7a63-11e6-8450-0605cc310205.png)
![foundation_rails_helper-after](https://cloud.githubusercontent.com/assets/1400414/18522107/8d0bfa24-7a63-11e6-8c0a-12757528b9ee.png)

**Comment by dsandstrom** [comment]
![foundation_rails_helper-callout](https://cloud.githubusercontent.com/assets/1400414/18522256/3d13c97e-7a64-11e6-9ee2-33adc93cd573.png)
