### ISSUE TITLE
Time for a new release

### ISSUE THREAD

**Issue by dsandstrom** [sgruhier/foundation_rails_helper#89]
I think we should go with v1.0.

@dgmstuart Can you update rubygems.  If not, @sgruhier, my email is darrell.sandstrom [at] gmail.com

**Comment by dgmstuart** [comment]
@dsandstrom Sure I can do it. Is there anything else that needs to be added to the changelog apart from bugfixes? Maybe a note about the updates you've made to support the latest version of Foundation (and Rails?) would be useful.

Going to 1.0.0 means declaring "The api is stable and we won't change it any time soon" right? http://semver.org/spec/v2.0.0.html I guess that's true? Happy to agree on that basis

**Comment by dsandstrom** [comment]
I'll update the change log.

**Comment by dsandstrom** [comment]
As for the API, it is largely based on Rails.  Except, `label` and `label_options`, which shouldn't be changing.

**Comment by dgmstuart** [comment]
OK Cool. Shall I just add "bugfixes" and "Updated to be compatible with 5.2.2"  to the changelog then?

**Comment by dsandstrom** [comment]
That works for me.  The other major change was updating the tests for RSpec
3.  But, I don't think that needs to go in the change log because it only
impacts contributors.

**Comment by dgmstuart** [comment]
Version 1.0.0 exists: https://rubygems.org/gems/foundation_rails_helper

I've also created a v1.0.0 tag

**Comment by dsandstrom** [comment]
:+1:
