### ISSUE TITLE
Errors for nested forms

### ISSUE THREAD

**Issue by lessless** [sgruhier/foundation_rails_helper#97]
Hello! Are nested form errors supported?

**Comment by dgmstuart** [comment]
I thought so - have you come across a case where they aren't? If so, please show some example code so that we can investigate.

**Comment by lessless** [comment]
@dgmstuart sure they are! was a flack on my side, sorry for that ;)

**Comment by dgmstuart** [comment]
@lessless no problem. Best of luck with your project :)
